# This workflow CI checks the Java project
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java2Rust CI

on: [push]
  #push:
  #  branches: [ master, bump-to-java-11 ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    name: mvn verify (Java ${{ matrix.java }})
    runs-on: ubuntu-latest

    # We run parallel builds for the following Java versions
    strategy:
      matrix:
        java: [ 11, 17 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ''${{ matrix. java }}'
          cache: 'maven'

      - name: Run mvn verify
        run: mvn verify -B -ntp
