# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java2Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: mvn verify (Java ${{ matrix.java }})
    runs-on: ubuntu-latest

    # We run parallel builds for the following Java versions
    strategy:
      matrix:
        java: [ 11, 17 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-java-${{ matrix.java }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-java-${{ matrix.java }}-m2

      - name: Run mvn verify
        working-directory: ./sormas-base
        run: mvn verify -B -ntp
